### ISSUE TITLE
[bug] bad coloring on windows

### ISSUE THREAD

**Issue by d4rckh** [d4rckh/vaf#16]
**Describe the bug**
Color codes are not working properly on cmd.exe

**Expected behavior**
Text should be properly colored on all platforms

**Screenshots**
![image](https://user-images.githubusercontent.com/35298550/162613156-64729836-f650-4e71-8b7d-75ffd9433718.png)

**Operating system (please complete the following information):**
 - OS: Windows 10

**Comment by daanbreur** [comment]
We could use this: 

https://github.com/daanbreur/AdventofCode/blob/ebc3aafa1091c643a45054c2097446d30f4cb45b/2021/launcher.py#L31-L32

I wrote it a while ago in python but ansi is ansi.
Im not sure if it works on linux though. Probably only in TrueColor terminals

**Comment by d4rckh** [comment]
> We could use this:
> 
> https://github.com/daanbreur/AdventofCode/blob/ebc3aafa1091c643a45054c2097446d30f4cb45b/2021/launcher.py#L31-L32
> 
> I wrote it a while ago in python but ansi is ansi. Im not sure if it works on linux though. Probably only in TrueColor terminals

we can

**Comment by d4rckh** [comment]
fixed in v2
